### ISSUE TITLE
Translation of phrases with links

### ISSUE THREAD

**Issue by yolile** [open-contracting/spoonbill-web#270]
Currently, all the phrases with links eg "Data Review Tool" are translated as separated strings in transifex. We should consider a way to have them in the same paragraph where they are mentioned, instead of in separated strings. E.g. in https://github.com/open-contracting/spoonbill-web/blob/83ef61cfc33eb36359c393c12b75d3f81db8e589/frontend/src/views/UploadFile/index.vue#L41-L54

we should consider using the same `translate` tag for the complete paragraph

**Comment by sorenabell** [comment]
The issue was fixed. Please check.

**Comment by yolile** [comment]
Hmm I still see the strings as separate strings in transifex and in the code 
![image](https://user-images.githubusercontent.com/6834122/135851132-1861f380-71d0-4c93-916c-804c2d039084.png)
https://github.com/open-contracting/spoonbill-web/blob/f0c99526c0608832bbd6e3731d357f52c1f8d9ca/frontend/src/views/UploadFile/index.vue#L50-L64

**Comment by sorenabell** [comment]
But the text on UI is translated?

**Comment by jpmckinney** [comment]
I think we can leave this as a low-priority cleanup task, which OCP can do at some time.
